### ISSUE TITLE
Line break removed when preceded by space

### ISSUE THREAD

**Issue by marcusclip** [bleargh45/JavaScript-Minifier-XS#8] opened 2021-10-15 00:51 UTC
Seems there is an issue if a line ends in space followed by line break, i.e. 0x20 0x0a. In that case the line break is removed, thereby creating a single line, which can produce invalid javascript.

Example:

var a=3 
var b=5

Make sure the first line is ended with 0x20 0x0a. The minification produces:

var a=3 var b=5

which is invalid javascript.

Thanks!

**Comment by bleargh45** [comment] 2021-10-16 03:23
I just pushed a v0.15 release out, which _should_ fix that in a67c2ab9.

Would you mind taking this new release for a spin, and seeing if that works any better for you?

**Comment by bleargh45** [comment] 2021-10-18 03:05
@marcusclip thank you for replying via email, to let me know this works as intended for you.  Closing issue.  :)

**Closed as completed by bleargh45** 2021-10-18 03:05 UTC
